/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-01-11 07:25:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.IntroCharacter;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mapLine_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../bootstrap/css/bootstrap.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("\r\n");
      out.write("<!-- FONTAWESOME STYLES-->\r\n");
      out.write("<link href=\"../assets/css/font-awesome.css\" rel=\"stylesheet\" />\r\n");
      out.write("<!-- MORRIS CHART STYLES-->\r\n");
      out.write("<link href=\"../assets/js/morris/morris-0.4.3.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<!-- CUSTOM STYLES-->\r\n");
      out.write("<link href=\"../assets/css/custom.css\" rel=\"stylesheet\" />\r\n");
      out.write("<!-- GOOGLE FONTS-->\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Open+Sans'\r\n");
      out.write("\trel='stylesheet' type='text/css' />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../bootstrap/css/login.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Website Font style -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- services 라이브러리 불러오기 -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"//apis.daum.net/maps/maps3.js?apikey=APIKEY&libraries=services\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- services와 clusterer, drawing 라이브러리 불러오기 -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"//apis.daum.net/maps/maps3.js?apikey=APIKEY&libraries=services,clusterer,drawing\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Map Line</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- main페이지! -->\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-default navbar-cls-top \" role=\"navigation\"\r\n");
      out.write("\t\t\tstyle=\"margin-bottom: 0; background-color: #14d68d;\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\".sidebar-collapse\">\r\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"../index.jsp\">BB's Shop</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div\r\n");
      out.write("\t\t\t\tstyle=\"color: white; padding: 15px 50px 5px 50px; float: right; font-size: 16px;\">\r\n");
      out.write("\t\t\t\tWelcome :) <a href=\"../Login/logout.jsp\">LogOut</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<!-- /. NAV TOP  -->\r\n");
      out.write("\t\t<nav class=\"navbar-default navbar-side\" role=\"navigation\">\r\n");
      out.write("\t\t\t<div class=\"sidebar-collapse\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav\" id=\"main-menu\">\r\n");
      out.write("\t\t\t\t\t<li><img style=\"size: 5px\" src=\"../images/main.png\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"img-responsive img-circle\"></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"../index.jsp\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-user-circle fa-3x\"></i> Intro</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-sitemap fa-3x\"></i> 캐릭터 소개<span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa arrow\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav nav-second-level\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"active-menu\" href=\"introLine.jsp\">라인 프렌즈</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Second Level Link</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Second Level Link<span class=\"fa arrow\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"nav nav-third-level\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Third Level Link</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Third Level Link</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Third Level Link</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ui.html\"><i class=\"fa fa-desktop fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\tUI Elements</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"tab-panel.html\"><i class=\"fa fa-qrcode fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\tTabs Panels</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"chart.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-bar-chart-o fa-3x\"></i> Morris Charts</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"table.html\"><i class=\"fa fa-table fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\tTable Examples</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"form.html\"><i class=\"fa fa-edit fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\tForms </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login.html\"><i class=\"fa fa-bolt fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\tLogin</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"registeration.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-laptop fa-3x\"></i> Registeration</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-sitemap fa-3x\"></i>\r\n");
      out.write("\t\t\t\t\t\t\tMulti-Level Dropdown<span class=\"fa arrow\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav nav-second-level\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Second Level Link</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Second Level Link</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Second Level Link<span class=\"fa arrow\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"nav nav-third-level\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Third Level Link</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Third Level Link</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Third Level Link</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 여기부터 소스코드 넣기!!!!!! -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"map\" style=\"margin-left: 40%; width: 500px; height: 400px;\"></div>\r\n");
      out.write("\t\t<script type=\"text/javascript\"\r\n");
      out.write("\t\t\tsrc=\"//apis.daum.net/maps/maps3.js?apikey=3dcb0205e8fa47adeac40bbf15979f13\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tvar container = document.getElementById('map');\r\n");
      out.write("\t\t\tvar options = {//지도 생성\r\n");
      out.write("\t\t\t\tcenter : new daum.maps.LatLng(37.519995, 127.022807),//지도의 중심좌표 -> \r\n");
      out.write("\t\t\t\tlevel : 3,//지도 레벨\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar map = new daum.maps.Map(container, options);//맵그림\r\n");
      out.write("\r\n");
      out.write("\t\t\t//마커 설정 \r\n");
      out.write("\t\t\tvar marker = new daum.maps.Marker({\r\n");
      out.write("\t\t\t\tposition : new daum.maps.LatLng(37.519995, 127.022807)\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tmarker.setMap(map);\r\n");
      out.write("\r\n");
      out.write("\t\t\t//문구 설정 \r\n");
      out.write("\t\t\tvar infowindow = new daum.maps.InfoWindow({\r\n");
      out.write("\t\t\t\tcontent : '신사동 라인 스토어'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tinfowindow.open(map, marker);\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /. WRAPPER  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->\r\n");
      out.write("\t<!-- JQUERY SCRIPTS -->\r\n");
      out.write("\t<script src=\"../assets/js/jquery-1.10.2.js\"></script>\r\n");
      out.write("\t<!-- BOOTSTRAP SCRIPTS -->\r\n");
      out.write("\t<script src=\"../assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- METISMENU SCRIPTS -->\r\n");
      out.write("\t<script src=\"../assets/js/jquery.metisMenu.js\"></script>\r\n");
      out.write("\t<!-- MORRIS CHART SCRIPTS -->\r\n");
      out.write("\t<script src=\"../assets/js/morris/raphael-2.1.0.min.js\"></script>\r\n");
      out.write("\t<script src=\"../assets/js/morris/morris.js\"></script>\r\n");
      out.write("\t<!-- CUSTOM SCRIPTS -->\r\n");
      out.write("\t<script src=\"../assets/js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
